In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('Social_Network_Ads.csv')

In [3]:
dataset.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
dataset.drop(['User ID'],axis=1,inplace=True)

In [5]:
dataset.head()

Gender  Age  EstimatedSalary  Purchased
0    Male   19            19000          0
1    Male   35            20000          0
2  Female   26            43000          0
3  Female   27            57000          0
4    Male   19            76000          0

In [6]:
dataset['Gender']=pd.get_dummies(dataset['Gender'],drop_first=True)

In [7]:
dataset.head()

Gender  Age  EstimatedSalary  Purchased
0       1   19            19000          0
1       1   35            20000          0
2       0   26            43000          0
3       0   27            57000          0
4       1   19            76000          0

In [8]:
dataset.shape

(400, 4)

In [9]:
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
print(X_train)

[[-0.98019606  0.58164944 -0.88670699]
 [ 1.02020406 -0.60673761  1.46173768]
 [-0.98019606 -0.01254409 -0.5677824 ]
 [-0.98019606 -0.60673761  1.89663484]
 [-0.98019606  1.37390747 -1.40858358]
 [-0.98019606  1.47293972  0.99784738]
 [ 1.02020406  0.08648817 -0.79972756]
 [ 1.02020406 -0.01254409 -0.24885782]
 [-0.98019606 -0.21060859 -0.5677824 ]
 [-0.98019606 -0.21060859 -0.19087153]
 [-0.98019606 -0.30964085 -1.29261101]
 [ 1.02020406 -0.30964085 -0.5677824 ]
 [ 1.02020406  0.38358493  0.09905991]
 [-0.98019606  0.8787462  -0.59677555]
 [-0.98019606  2.06713324 -1.17663843]
 [ 1.02020406  1.07681071 -0.13288524]
 [-0.98019606  0.68068169  1.78066227]
 [-0.98019606 -0.70576986  0.56295021]
 [-0.98019606  0.77971394  0.35999821]
 [-0.98019606  0.8787462  -0.53878926]
 [ 1.02020406 -1.20093113 -1.58254245]
 [ 1.02020406  2.1661655   0.93986109]
 [-0.98019606 -0.01254409  1.22979253]
 [ 1.02020406  0.18552042  1.08482681]
 [-0.98019606  0.38358493 -0.48080297]
 [ 1.02020406 -0.30964085

In [13]:
print(X_test)

[[ 1.02020406 -0.80480212  0.50496393]
 [-0.98019606 -0.01254409 -0.5677824 ]
 [ 1.02020406 -0.30964085  0.1570462 ]
 [-0.98019606 -0.80480212  0.27301877]
 [-0.98019606 -0.30964085 -0.5677824 ]
 [ 1.02020406 -1.10189888 -1.43757673]
 [-0.98019606 -0.70576986 -1.58254245]
 [ 1.02020406 -0.21060859  2.15757314]
 [-0.98019606 -1.99318916 -0.04590581]
 [ 1.02020406  0.8787462  -0.77073441]
 [ 1.02020406 -0.80480212 -0.59677555]
 [-0.98019606 -1.00286662 -0.42281668]
 [ 1.02020406 -0.11157634 -0.42281668]
 [ 1.02020406  0.08648817  0.21503249]
 [ 1.02020406 -1.79512465  0.47597078]
 [-0.98019606 -0.60673761  1.37475825]
 [ 1.02020406 -0.11157634  0.21503249]
 [ 1.02020406 -1.89415691  0.44697764]
 [-0.98019606  1.67100423  1.75166912]
 [ 1.02020406 -0.30964085 -1.37959044]
 [-0.98019606 -0.30964085 -0.65476184]
 [-0.98019606  0.8787462   2.15757314]
 [-0.98019606  0.28455268 -0.53878926]
 [ 1.02020406  0.8787462   1.02684052]
 [-0.98019606 -1.49802789 -1.20563157]
 [-0.98019606  1.07681071

In [14]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state = 0)
model.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [15]:
y_pred = model.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]]


In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[65  3]
 [ 7 25]]


0.9